server:
  port: 8082
spring:
  application:
    name: product
  datasource:
    username: 'amigoscode'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/product
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true